/* ============================================================
   Abberanth Companion - Spell Data
   Auto-generated - edit descriptions here as needed.
   ============================================================ */

window.SPELL_DATA = [
  {
    id:      "mend",
    name:    "Mend",
    cost:    1,
    wells:   null,
    desc:    `Fix an item or small structure within a 5×5 meter cube. Examples: a small chunk of wall, a pocket watch.`,
    scaling: null,
  },
  {
    id:      "candle",
    name:    "Candle",
    cost:    1,
    wells:   null,
    desc:    `Spark or snuff a candle-sized flame.`,
    scaling: null,
  },
  {
    id:      "breeze",
    name:    "Breeze",
    cost:    1,
    wells:   null,
    desc:    `Cool a 10×10 meter area with a gentle wind.`,
    scaling: null,
  },
  {
    id:      "aide",
    name:    "Aide",
    cost:    1,
    wells:   null,
    desc:    `Grant temporary 1d10 HP on a target. No dice explosion. Cannot regrow limbs, remove scars, or stop bleeding.`,
    scaling: null,
  },
  {
    id:      "puddle",
    name:    "Puddle",
    cost:    1,
    wells:   null,
    desc:    `Create a 12×12×1 cm puddle of clean water.`,
    scaling: null,
  },
  {
    id:      "magic-missile",
    name:    "Magic Missile",
    cost:    5,
    wells:   [{ name: "Arcane", minLevel: 1 }],
    desc:    `Create a singular missile of arcane nature. Each additional mana spent adds 1 bolt. Each bolt deals 1d10 damage.`,
    scaling: `+1 mana → +1 bolt (each bolt deals 1d10 damage)`,
  },
  {
    id:      "prestidigitation",
    name:    "Prestidigitation",
    cost:    5,
    wells:   [{ name: "Arcane", minLevel: 1 }],
    desc:    `Choose one effect (base duration 60 minutes). Adding 1 mana extends duration by 10 minutes or adds another effect.\\n\\nEffects:\\n• Ignite or snuff all candles, torches, or campfires in a 50×50 meter radius.\\n• Create a small sensory effect that deals no damage.\\n• Clean or soil an object within a 1×1 meter cube (add +1 meter per extra mana).\\n• Chill, warm, or flavor something within a 1×1 meter cube (add +1 meter per extra mana).\\n• Add colour, make a mark, or place a symbol on a structure.`,
    scaling: `+1 mana → +10 minutes duration, or add another effect`,
  },
  {
    id:      "ice",
    name:    "Ice",
    cost:    10,
    wells:   [{ name: "Arcane", minLevel: 2 }],
    desc:    `Fill a 5×5 meter area with a cube of ice. People within the zone must roll Speed vs your Arcane to dodge. If the target fails, they are frozen in place and take 2d10 damage at the start of each turn. Ice lasts for 5 rounds. Optionally, cast ice only on the ground in a 15×15 meter area — anyone crossing must move at half speed or roll Speed vs DC 15.`,
    scaling: `+1 mana → +1 meter to size, +1 round duration, or +1 to DC`,
  },
  {
    id:      "empower",
    name:    "Empower",
    cost:    10,
    wells:   [{ name: "Arcane", minLevel: 2 }],
    desc:    `Choose yourself or one allied creature. The next attack spell cast by that entity gets +5 to both the to-hit and damage roll.`,
    scaling: null,
  },
  {
    id:      "erupt",
    name:    "Erupt",
    cost:    15,
    wells:   [{ name: "Arcane", minLevel: 3 }],
    desc:    `The ground becomes a magma fissure in a 5×50 meter line, dealing damage relative to your Arcane dice on first impact. Heat radiates 15 meters either side of the fissure and deals 1d10 damage to anything that starts or ends its turn in the heat radius.`,
    scaling: `+1 mana → +1 meter to fissure size, or +1 direction change`,
  },
  {
    id:      "lift",
    name:    "Lift",
    cost:    15,
    wells:   [{ name: "Arcane", minLevel: 3 }],
    desc:    `Target any creature within 50 meters. If unwilling, they must roll a Strength save. On affected creatures, the caster can move the creature in any direction at the caster's speed. This uses only one move's worth of speed from the caster.`,
    scaling: `+1 mana → +1 creature or +1 move per mana`,
  },
  {
    id:      "scry",
    name:    "Scry",
    cost:    20,
    wells:   [{ name: "Arcane", minLevel: 4 }],
    desc:    `Choose a person or place you have seen or have an item from. For 10 minutes, you can see through the person's eyes or view the general location.`,
    scaling: `+1 mana → +1 minute duration, or switch target`,
  },
  {
    id:      "arcane-barrier",
    name:    "Arcane Barrier",
    cost:    20,
    wells:   [{ name: "Arcane", minLevel: 4 }],
    desc:    `Choose a willing target and cast a 10-meter barrier around them. The barrier adds 10 to their AC and grants 10 Temporary HP when it breaks.`,
    scaling: `+5 mana → +1 AC; +1 mana → +1 HP`,
  },
  {
    id:      "elemental-surge",
    name:    "Elemental Surge",
    cost:    25,
    wells:   [{ name: "Arcane", minLevel: 5 }],
    desc:    `Pick one element within 60 meters of you. In a 20-meter radius, that element surges forth dealing Arcane damage to the target. The surge continues for ten rounds.`,
    scaling: `+1 mana → new explosion elsewhere, or +5 meters to radius`,
  },
  {
    id:      "mana-vortex",
    name:    "Mana Vortex",
    cost:    25,
    wells:   [{ name: "Arcane", minLevel: 5 }],
    desc:    `Roll an attack against a target's AC. On success, roll your Arcane and steal that amount of mana from the target, adding it to the damage of your next spell.`,
    scaling: null,
  },
  {
    id:      "storm-call",
    name:    "Storm Call",
    cost:    30,
    wells:   [{ name: "Arcane", minLevel: 6 }],
    desc:    `Create a dark storm cloud over a 50×50 meter area. Within that area plus 20 meters, you may perform 3 lightning strikes per attack. Each strike requires an attack roll and deals Arcane damage. The storm lasts 10 rounds.`,
    scaling: null,
  },
  {
    id:      "arcane-infusion",
    name:    "Arcane Infusion",
    cost:    30,
    wells:   [{ name: "Arcane", minLevel: 6 }],
    desc:    `Pick an ally or a weapon and imbue them with an element that deals your Arcane score in damage.`,
    scaling: null,
  },
  {
    id:      "elemental-fusion",
    name:    "Elemental Fusion",
    cost:    35,
    wells:   [{ name: "Arcane", minLevel: 7 }],
    desc:    `Pick 2 elements and combine them within 100 meters.\\n\\n• Fire + Earth = Lava: 10×10 meter square, deals Arcane damage.\\n• Fire + Water = Steam: 10×10 meter square, deals Arcane damage.\\n• Fire + Wind = Tornado: 10×10 wide, moves to your will, deals Arcane damage.\\n• Earth + Water = Mud: 40×40 area, slows speed by half.\\n• Earth + Wind = Sandstorm: 40×40 area, ripping sand deals Arcane damage and slows speed by 10.\\n• Water + Wind = Hurricane: 10×10 wide, moves to your will, deals Arcane damage.`,
    scaling: null,
  },
  {
    id:      "energy-cascade",
    name:    "Energy Cascade",
    cost:    35,
    wells:   [{ name: "Arcane", minLevel: 7 }],
    desc:    `Pick a target and roll your Arcane to attack. If you beat their AC, roll damage then pick another target adding 1 to their AC. If you continue to succeed, keep bouncing the spell between targets.`,
    scaling: null,
  },
  {
    id:      "elemental-damnation",
    name:    "Elemental Damnation",
    cost:    40,
    wells:   [{ name: "Arcane", minLevel: 8 }],
    desc:    `Pick a target and an element. They must roll their Speed against your Arcane. On success, they take half damage. On failure, they take full elemental damage and must spend 1d10 actions to free themselves from their elemental prison.`,
    scaling: null,
  },
  {
    id:      "primal-unleash",
    name:    "Primal Unleash",
    cost:    40,
    wells:   [{ name: "Arcane", minLevel: 8 }],
    desc:    `In a 100-meter radius around you, you well up the natural mana in all things, causing one element to react violently. Everyone including you must make Speed saves every round they enter or end inside the afflicted area.`,
    scaling: null,
  },
  {
    id:      "arcane-dominion",
    name:    "Arcane Dominion",
    cost:    45,
    wells:   [{ name: "Arcane", minLevel: 9 }],
    desc:    `In a 500-meter radius, you control the elements. You can make air solid to form walls, make fire erupt from the ground, turn water to ice, stone to sand, and much more.`,
    scaling: null,
  },
  {
    id:      "elemental-avatar",
    name:    "Elemental Avatar",
    cost:    45,
    wells:   [{ name: "Arcane", minLevel: 9 }],
    desc:    `Choose one element and create an Avatar out of it. All actions the Avatar takes add your Arcane score worth of that element's damage.`,
    scaling: null,
  },
  {
    id:      "arcane-meteors",
    name:    "Arcane Meteors",
    cost:    50,
    wells:   [{ name: "Arcane", minLevel: 10 }],
    desc:    `In a 1,000-meter radius, a storm brews. You can cast 10 flaming meteors (5 meters each) per action until you dispel it. Each meteor deals Arcane damage.`,
    scaling: null,
  },
  {
    id:      "mana-apocalypse",
    name:    "Mana Apocalypse",
    cost:    50,
    wells:   [{ name: "Arcane", minLevel: 10 }],
    desc:    `Mana erupts in a 500-meter radius. All within must make a Dexterity save. The explosion deals Arcane damage; half on a successful save.`,
    scaling: null,
  },
  {
    id:      "minor-lift",
    name:    "Minor Lift",
    cost:    10,
    wells:   [{ name: "Arcane", minLevel: 1 }, { name: "Order", minLevel: 1 }],
    desc:    `Within 100 meters, you can lift a small item (like a cup or a book) with your mind and control where it goes.`,
    scaling: null,
  },
  {
    id:      "kinetic-grasp",
    name:    "Kinetic Grasp",
    cost:    40,
    wells:   [{ name: "Arcane", minLevel: 4 }, { name: "Order", minLevel: 1 }],
    desc:    `Allows control over a medium-sized item (like a chair or a weapon) at up to 100 meters.`,
    scaling: null,
  },
  {
    id:      "mass-manipulation",
    name:    "Mass Manipulation",
    cost:    70,
    wells:   [{ name: "Arcane", minLevel: 7 }, { name: "Order", minLevel: 1 }],
    desc:    `Manipulate medium to large-sized objects to form barriers. Medium items have 5 AC and large items have 10 AC.`,
    scaling: null,
  },
  {
    id:      "reality-bend",
    name:    "Reality Bend",
    cost:    100,
    wells:   [{ name: "Arcane", minLevel: 10 }, { name: "Order", minLevel: 1 }],
    desc:    `Can lift and throw any object or person up to huge size, including buildings.`,
    scaling: null,
  },
  {
    id:      "force-push",
    name:    "Force Push",
    cost:    20,
    wells:   [{ name: "Arcane", minLevel: 2 }, { name: "Chaos", minLevel: 1 }],
    desc:    `Aim at an object or person. If unwilling, roll your Arcane vs their Wisdom. If they fail, roll a d10 for direction (1=left, 2=right, 3=forward, 4=backwards, 5=forward-left, 6=forward-right, 7=back-left, 8=back-right, 9=up, 10=down). The target is shoved 20 meters in that direction. Damage is caused if they hit a solid object.`,
    scaling: null,
  },
  {
    id:      "chaos-fling",
    name:    "Chaos Fling",
    cost:    80,
    wells:   [{ name: "Arcane", minLevel: 8 }, { name: "Chaos", minLevel: 1 }],
    desc:    `All objects and people up to large size within 100 meters of you get flung 40 meters away. All affected must make a Speed save to land safely.`,
    scaling: null,
  },
  {
    id:      "temporal-shove",
    name:    "Temporal Shove",
    cost:    50,
    wells:   [{ name: "Arcane", minLevel: 5 }, { name: "Time", minLevel: 1 }],
    desc:    `You build up an explosive force over time, launching a medium-sized object with extreme force. Roll your Arcane against their AC; on hit, deal Arcane damage and 1d10 time damage over the next 1d10 turns.`,
    scaling: null,
  },
  {
    id:      "spell-deflect",
    name:    "Spell Deflect",
    cost:    60,
    wells:   [{ name: "Arcane", minLevel: 6 }, { name: "Fortitude", minLevel: 1 }],
    desc:    `Cast as a reaction to a spell attack. Roll your Arcane against their Arcane. If you win, you take no damage and bounce half the caster's damage back upon them.`,
    scaling: null,
  },
  {
    id:      "needles",
    name:    "Needles",
    cost:    5,
    wells:   [{ name: "Chaos", minLevel: 1 }],
    desc:    `Summon 5 needles. Each needle when thrown deals 1d10 damage.`,
    scaling: null,
  },
  {
    id:      "smudge",
    name:    "Smudge",
    cost:    5,
    wells:   [{ name: "Chaos", minLevel: 1 }],
    desc:    `Choose an area within 50 meters and make a mark from 1cm×1cm to 10×10 meters. Lasts 1 hour. Can mark living creatures. Cannot be removed until it times out or a cleaning spell is used.`,
    scaling: `+1 mana → +10 minutes duration`,
  },
  {
    id:      "chaos-spark",
    name:    "Chaos Spark",
    cost:    10,
    wells:   [{ name: "Chaos", minLevel: 2 }],
    desc:    `Shoot out an element in a 50-meter straight line. You will not know the element — the GM will. The element deals Chaos damage. There is also a 20% chance of it rebounding.`,
    scaling: null,
  },
  {
    id:      "erratic-summon",
    name:    "Erratic Summon",
    cost:    10,
    wells:   [{ name: "Chaos", minLevel: 2 }],
    desc:    `You summon a small Chaos Spirit.`,
    scaling: null,
  },
  {
    id:      "wild-ripple",
    name:    "Wild Ripple",
    cost:    15,
    wells:   [{ name: "Chaos", minLevel: 3 }],
    desc:    `Releases a wave of chaos causing nearby creatures (including allies) to suffer random minor effects — temporary buffs, debuffs, colour changes, or sudden polymorphs into small animals.`,
    scaling: null,
  },
  {
    id:      "fractured-portal",
    name:    "Fractured Portal",
    cost:    15,
    wells:   [{ name: "Chaos", minLevel: 3 }],
    desc:    `Opens a tiny, unstable rift to summon random minor creatures or objects from other planes. Roll to determine if it's helpful (ally), hostile, or just weird junk.`,
    scaling: null,
  },
  {
    id:      "unstable-augment",
    name:    "Unstable Augment",
    cost:    20,
    wells:   [{ name: "Chaos", minLevel: 4 }],
    desc:    `Target an ally or yourself with chaotic energy, granting a random powerful boon for a short time (extra damage, flight, invisibility, etc.), but with a risk of backlash surge afterward.`,
    scaling: null,
  },
  {
    id:      "chaos-bind",
    name:    "Chaos Bind",
    cost:    20,
    wells:   [{ name: "Chaos", minLevel: 4 }],
    desc:    `Summons chaotic tendrils that restrain a target unpredictably — might hold them perfectly, lash out at others, or turn into harmless butterflies.`,
    scaling: null,
  },
  {
    id:      "rift-cascade",
    name:    "Rift Cascade",
    cost:    25,
    wells:   [{ name: "Chaos", minLevel: 5 }],
    desc:    `Tears open multiple small portals in an area, spewing random summoned creatures (some fight for you, some against, some neutral) that last only briefly before vanishing.`,
    scaling: null,
  },
  {
    id:      "entropy-burst",
    name:    "Entropy Burst",
    cost:    25,
    wells:   [{ name: "Chaos", minLevel: 5 }],
    desc:    `Unleashes a blast of pure disorder that weakens structures, disrupts spells being cast, and causes random wild magic surges in the area.`,
    scaling: null,
  },
  {
    id:      "chaotic-menagerie",
    name:    "Chaotic Menagerie",
    cost:    30,
    wells:   [{ name: "Chaos", minLevel: 6 }],
    desc:    `Summons a pack of bizarre, ever-shifting creatures (roll for types each round: wolves one moment, flaming elementals the next) that obey poorly and change allegiance randomly.`,
    scaling: null,
  },
  {
    id:      "wild-gamble",
    name:    "Wild Gamble",
    cost:    30,
    wells:   [{ name: "Chaos", minLevel: 6 }],
    desc:    `Forces a target to roll on a mini wild magic table — could heal them massively, polymorph them, teleport them, or trigger catastrophic failure.`,
    scaling: null,
  },
  {
    id:      "anarchy-storm",
    name:    "Anarchy Storm",
    cost:    35,
    wells:   [{ name: "Chaos", minLevel: 7 }],
    desc:    `Calls a storm of chaotic energy raining random effects across a large area: lightning, fireballs, healing rain, polymorphing bolts, or sudden gravity flips.`,
    scaling: null,
  },
  {
    id:      "unreliable-ally",
    name:    "Unreliable Ally",
    cost:    35,
    wells:   [{ name: "Chaos", minLevel: 7 }],
    desc:    `Summons a powerful but fickle greater chaos entity that aids you aggressively... until it might betray you or warp reality around it.`,
    scaling: null,
  },
  {
    id:      "reality-fracture",
    name:    "Reality Fracture",
    cost:    40,
    wells:   [{ name: "Chaos", minLevel: 8 }],
    desc:    `Shatters local reality, creating zones of wild magic where spells trigger extra surges, summons appear spontaneously, and physics bends erratically.`,
    scaling: null,
  },
  {
    id:      "pandemonium-call",
    name:    "Pandemonium Call",
    cost:    40,
    wells:   [{ name: "Chaos", minLevel: 8 }],
    desc:    `Summons a horde of lesser chaotic beings that swarm enemies, but the horde grows or shrinks unpredictably and might turn on the caster.`,
    scaling: null,
  },
  {
    id:      "chaos-dominion",
    name:    "Chaos Dominion",
    cost:    45,
    wells:   [{ name: "Chaos", minLevel: 9 }],
    desc:    `What is gravity in a 50 meter radius?`,
    scaling: null,
  },
  {
    id:      "entropy-sovereign",
    name:    "Entropy Sovereign",
    cost:    45,
    wells:   [{ name: "Chaos", minLevel: 9 }],
    desc:    `Temporarily become a conduit of ultimate disorder, gaining immense power (random massive buffs each turn) but risking permanent mutation or banishment to a chaotic plane.`,
    scaling: null,
  },
  {
    id:      "complete-chaos",
    name:    "Complete Chaos",
    cost:    50,
    wells:   [{ name: "Chaos", minLevel: 10 }],
    desc:    `Create an area of 500 meters. You can control 1 change per move in this bubble. Reality belongs to you.`,
    scaling: `+1 mana → +10 meters`,
  },
  {
    id:      "alpha",
    name:    "Alpha",
    cost:    50,
    wells:   [{ name: "Chaos", minLevel: 10 }],
    desc:    `Pick your target, If they have less than 200 mana, make a spell check against their AC. If you hit and aren't interrupted, you force mana into the target and they explode. The explosion takes up a 100x100 meter cube.`,
    scaling: null,
  },
  {
    id:      "minor-armament",
    name:    "Minor Armament",
    cost:    10,
    wells:   [{ name: "Chaos", minLevel: 1 }, { name: "Fortitude", minLevel: 1 }],
    desc:    `You can cunjure a small knife or dagger. It does 1d10k1e10 damage.`,
    scaling: null,
  },
  {
	  id:	"armament",
	  name:	"Armament",
	  cost:	20,
	  wells:	[{ name: "Chaos", minLevel: 2}, {name: "Fortitude", minLevel: 1 }],
	  desc:	`You may conjure a small to medium sized weapon that does up to 3d10k1e10 damage.`,
	  scaling: null,
  },
  {
	  id: "lancer",
	  name: "Lancer",
	  cost: 30,
	  wells: [{name: "Chaos", minLevel: 3}, {name: "Fortitude", minLevel: 1 }],
	  desc: `You may cunjure a lance that has a tip which explodes as a random element per hit. 1 - fire, 2 - ice, 3 - water, 4 - dirt, 5 - rock, 6 - lightning, 7 - wind, 8 - chaos spirits, 9 - lava, 10 - sheer force. The lance does 3d10k2 damage and the explosion does 4d10k3.`,
	  scaling: null,
  },
  {
    id:      "conjure-arsenal",
    name:    "Conjure Arsenal",
    cost:    40,
    wells:   [{ name: "Chaos", minLevel: 4 }, { name: "Fortitude", minLevel: 1 }],
    desc:    `You can cunjure up to 5 weapons.`,
    scaling: null,
  },
  {
	  id:	"chaos-armor",
	  name: "Chaos Armor",
	  cost:	50,
	  wells: [{name: "Chaos", minLevel: 5 }, {name: "Fortitude", minLevel: 1 }],
	  desc:	`You or an ally are covered by a black, purple, and blue layer that looks like small flames licking off the body. This armor can absorb up to 10 attacks then disappates, unless you expel the attacks in tandem with your own or as a reaction.`,
	  scaling: null,
  },
  {
    id:      "legion-s-edge",
    name:    "Legion's Edge",
    cost:    70,
    wells:   [{ name: "Chaos", minLevel: 7 }, { name: "Fortitude", minLevel: 1 }],
    desc:    `You may conjure one weapon that does 10d10k10e10 damage.`,
    scaling: null,
  },
  {
    id:      "apocalypse-armory",
    name:    "Apocalypse Armory",
    cost:    100,
    wells:   [{ name: "Chaos", minLevel: 10 }, { name: "Fortitude", minLevel: 1 }],
    desc:    `At base, summon 10 weapons. oer each extra mana, summon 1 more.`,
    scaling: null,
  },
  {
    id:      "errant-blade",
    name:    "Errant Blade",
    cost:    20,
    wells:   [{ name: "Chaos", minLevel: 2 }, { name: "Arcane", minLevel: 1 }],
    desc:    `Summons a basic melee weapon (sword or axe) infused with raw elemental energy (random fire/ice), which fizzles or surges wildly due to chaos.`,
    scaling: null,
  },
  {
    id:      "volatile-hammer",
    name:    "Volatile Hammer",
    cost:    50,
    wells:   [{ name: "Chaos", minLevel: 5 }, { name: "Arcane", minLevel: 5 }],
    desc:    `Manifests a larger blunt weapon (warhammer or mace) crackling with raw magic, dealing bonus elemental damage but with a risk of chaotic backlash (e.g., hitting an ally).`,
    scaling: null,
  },
  {
    id:      "titan-s-cleaver",
    name:    "Titan's Cleaver",
    cost:    80,
    wells:   [{ name: "Chaos", minLevel: 8 }, { name: "Arcane", minLevel: 8 }],
    desc:    `Evokes a massive two-handed weapon (greatsword or greataxe) of pure elemental chaos, capable of cleaving through barriers but potentially destabilizing the environment.`,
    scaling: null,
  },
  {
    id:      "light",
    name:    "Light",
    cost:    5,
    wells:   [{ name: "Day", minLevel: 1 }],
    desc:    `Create an orb of light that floats within a meter of you, casting soft shadows. Lights up 10×10 meters in bright light and 30×30 in dim light.`,
    scaling: `+1 mana → +5 meters to light radius, or add another orb`,
  },
  {
    id:      "follow",
    name:    "Follow",
    cost:    5,
    wells:   [{ name: "Day", minLevel: 1 }],
    desc:    `Mark yourself or a creature with a trail of light. If unwilling, roll your Arcane vs their Willpower. The trail is visible to those you choose. It trails 50 meters behind the target then fades. Lasts 10 minutes.`,
    scaling: `+1 mana → +1 meter trail length, +1 minute duration, or +1 to contest DC`,
  },
  {
    id:      "dawn-s-gaze",
    name:    "Dawn's Gaze",
    cost:    10,
    wells:   [{ name: "Day", minLevel: 2 }],
    desc:    `Projects a 20-meter beam of revealing light. Pierces through illusions, invisibility, and disguises in its path, briefly revealing them and stunning them for 1d10 actions. Target must roll Speed vs your Day to dodge.`,
    scaling: null,
  },
  {
    id:      "radiant-flare",
    name:    "Radiant Flare",
    cost:    10,
    wells:   [{ name: "Day", minLevel: 2 }],
    desc:    `Release a burst of bright light in a 40-meter cone. Anyone in the cone is blinded for their next round and allies outside the cone gain advantage to attack enemies in the cone. Those in the cone roll Speed vs your Day to dodge.`,
    scaling: null,
  },
  {
    id:      "truth-s-glare",
    name:    "Truth's Glare",
    cost:    15,
    wells:   [{ name: "Day", minLevel: 3 }],
    desc:    `Forces a target to glow with inner light, preventing them from lying or hiding intentions—any deception causes them pain or reveals their words as false to listeners.`,
    scaling: null,
  },
  {
    id:      "solar-ward",
    name:    "Solar Ward",
    cost:    15,
    wells:   [{ name: "Day", minLevel: 3 }],
    desc:    `Creates a shimmering barrier of daylight around an ally or area that repels darkness-based effects, undead, or shadowy creatures, and slowly heals minor wounds over time through gentle radiance.`,
    scaling: null,
  },
  {
    id:      "illuminate-secrets",
    name:    "Illuminate Secrets",
    cost:    20,
    wells:   [{ name: "Day", minLevel: 4 }],
    desc:    `Bathes an area in penetrating light that reveals hidden doors, traps, invisible writing, or concealed auras (magical or otherwise), making them glow brightly for all to see.`,
    scaling: null,
  },
  {
    id:      "blazing-ray",
    name:    "Blazing Ray",
    cost:    20,
    wells:   [{ name: "Day", minLevel: 4 }],
    desc:    `Fires a focused lance of solar energy that deals radiant damage and has a chance to ignite flammable objects or leave lingering burns that prevent healing until exposed to more light.`,
    scaling: null,
  },
  {
    id:      "daybreak-surge",
    name:    "Daybreak Surge",
    cost:    25,
    wells:   [{ name: "Day", minLevel: 5 }],
    desc:    `Calls forth an artificial dawn in an area, dispelling magical darkness, ending charm/fear effects on allies, and granting temporary resistance to death or cold damage while weakening undead.`,
    scaling: null,
  },
  {
    id:      "revealing-aura",
    name:    "Revealing Aura",
    cost:    25,
    wells:   [{ name: "Day", minLevel: 5 }],
    desc:    `Surrounds the caster with an aura of pure light that automatically detects lies, illusions, or shapechangers within range, and causes such deceptions to falter or fail.`,
    scaling: null,
  },
  {
    id:      "solar-corona",
    name:    "Solar Corona",
    cost:    30,
    wells:   [{ name: "Day", minLevel: 6 }],
    desc:    `The caster emits a halo of intense sunlight that damages nearby enemies each turn with radiant energy, while revealing and suppressing any stealth or concealment attempts in the radius.`,
    scaling: null,
  },
  {
    id:      "purging-beam",
    name:    "Purging Beam",
    cost:    30,
    wells:   [{ name: "Day", minLevel: 6 }],
    desc:    `Channels a purifying ray that cleanses curses, diseases, or poisons from a target, while dealing extra damage to corrupted or undead beings as the light burns away impurity.`,
    scaling: null,
  },
  {
    id:      "eternal-daylight",
    name:    "Eternal Daylight",
    cost:    35,
    wells:   [{ name: "Day", minLevel: 7 }],
    desc:    `Transforms an area into perpetual bright daylight for an extended period, negating all forms of darkness magic, empowering light-based effects, and weakening night creatures or nocturnal powers.`,
    scaling: null,
  },
  {
    id:      "sunlit-judgement",
    name:    "Sunlit Judgement",
    cost:    35,
    wells:   [{ name: "Day", minLevel: 7 }],
    desc:    `Forces all creatures in an area to be judged by revealing light—hidden evils or lies manifest as burning marks, dealing damage proportional to their deceptions or corruption.`,
    scaling: null,
  },
  {
    id:      "radiant-nova",
    name:    "Radiant Nova",
    cost:    40,
    wells:   [{ name: "Day", minLevel: 8 }],
    desc:    `Explodes with a massive burst of solar power that blinds and scorches enemies across a wide area, while healing and empowering allies with bursts of vitality and clarity.`,
    scaling: null,
  },
  {
    id:      "veil-of-revelation",
    name:    "Veil of Revelation",
    cost:    40,
    wells:   [{ name: "Day", minLevel: 8 }],
    desc:    `Creates a massive zone where all illusions, invisibility, and falsehoods are stripped away permanently until the spell ends—everything is laid bare under unyielding daylight.`,
    scaling: null,
  },
  {
    id:      "celestial-ascendance",
    name:    "Celestial Ascendance",
    cost:    45,
    wells:   [{ name: "Day", minLevel: 9 }],
    desc:    `Temporarily transforms the caster into a being of pure sunlight, gaining flight, immunity to radiant/fire damage, enhanced revealing senses, and the ability to emit beams of truth-forcing light at will.`,
    scaling: null,
  },
  {
    id:      "apocalypse-dawn",
    name:    "Apocalypse Dawn",
    cost:    45,
    wells:   [{ name: "Day", minLevel: 9 }],
    desc:    `Summons a cataclysmic false dawn that floods the battlefield with overwhelming light, incinerating shadows/undead, shattering persistent illusions, and forcing profound revelations (e.g., hidden motives or weaknesses) on all present.`,
    scaling: null,
  },
  {
    id:      "the-sun",
    name:    "The Sun",
    cost:    50,
    wells:   [{ name: "Day", minLevel: 10 }],
    desc:    `You manufacture the epitome of light by creating a miniature star 100 meters in the air. Only the caster can see through the blinding light, which covers a 500-meter radius and deals xd10 damage (x = level cast at) on deployment. Creatures that cannot find shadow take an additional 1d10 damage per turn exposed. Can cause first, second, and third degree burns. Lasts 5 rounds.`,
    scaling: `+1 mana → +1 round duration`,
  },
  {
    id:      "the-cure",
    name:    "The Cure",
    cost:    50,
    wells:   [{ name: "Day", minLevel: 10 }],
    desc:    `You emanate a healing light. All allies within 100 meters lose all negative modifiers. Does not undo curses.`,
    scaling: `+1 mana → +10 meters to radius`,
  },
  {
    id:      "gleam-scan",
    name:    "Gleam Scan",
    cost:    10,
    wells:   [{ name: "Day", minLevel: 1 }, { name: "Order", minLevel: 1 }],
    desc:    `Within 20 meters, all hidden objects or illusions have their auras highlighted in your vision. Lasts 5 minutes.`,
    scaling: null,
  },
  {
    id:      "truth-pierce",
    name:    "Truth Pierce",
    cost:    30,
    wells:   [{ name: "Day", minLevel: 3 }, { name: "Night", minLevel: 1 }],
    desc:    `Pierces darkness or illusions on a target with revealing light, exposing their true form or intentions briefly.`,
    scaling: null,
  },
  {
    id:      "foresight-beam",
    name:    "Foresight Beam",
    cost:    50,
    wells:   [{ name: "Day", minLevel: 5 }, { name: "Time", minLevel: 1 }],
    desc:    `Projects a light ray that glimpses a target's near-future actions, highlighting vulnerabilities in radiant outline.`,
    scaling: null,
  },
  {
    id:      "aura-unveil",
    name:    "Aura Unveil",
    cost:    70,
    wells:   [{ name: "Day", minLevel: 7 }, { name: "Life", minLevel: 1 }],
    desc:    `Bathes an area in purifying light to reveal life forces, detecting poisons, diseases, or disguised vitality drains.`,
    scaling: null,
  },
  {
    id:      "solar-insight",
    name:    "Solar Insight",
    cost:    80,
    wells:   [{ name: "Day", minLevel: 8 }, { name: "Arcane", minLevel: 1 }],
    desc:    `Channels raw energy through daylight to scry distant locations, revealing elemental weaknesses or hidden threats.`,
    scaling: null,
  },
  {
    id:      "omnisight-dawn",
    name:    "Omnisight Dawn",
    cost:    100,
    wells:   [{ name: "Day", minLevel: 10 }, { name: "Chaos", minLevel: 1 }],
    desc:    `Floods a zone with chaotic revealing light, randomly exposing all secrets/deceptions with unpredictable intensity.`,
    scaling: null,
  },
  {
    id:      "wither",
    name:    "Wither",
    cost:    5,
    wells:   [{ name: "Death", minLevel: 1 }],
    desc:    `Objects around you in a 5-meter radius begin to wither. Deals 1d10 damage per turn to anything in your aura. Lasts 5 rounds.`,
    scaling: `+1 mana → +1d10 damage, +1 meter radius, or +1 round duration`,
  },
  {
    id:      "writhe",
    name:    "Writhe",
    cost:    5,
    wells:   [{ name: "Death", minLevel: 1 }],
    desc:    `This spell makes the target feel as if something is moving beneath their flesh. Roll your Death vs their Willpower. On failure, the target has −1 to their totals for the next 5 rounds.`,
    scaling: `+1 mana → +1 to DC, −1 additional penalty, or +1 round duration`,
  },
  {
    id:      "fevered-touch",
    name:    "Fevered Touch",
    cost:    10,
    wells:   [{ name: "Death", minLevel: 2 }],
    desc:    `Touch your enemy to inflict a fever. Every round until the fever is healed, inflict escalating damage. First turn: 1d10+Death, second turn: 2d10+Death, and so on.`,
    scaling: null,
  },
  {
    id:      "speak-with-departed",
    name:    "Speak with Departed",
    cost:    10,
    wells:   [{ name: "Death", minLevel: 2 }],
    desc:    `Find a corpse no more than 24 hours old. You may ask it three questions. Answers will often be vague or cryptic and can only cover what it knew in life.`,
    scaling: null,
  },
  {
    id:      "wasting-plague",
    name:    "Wasting Plague",
    cost:    15,
    wells:   [{ name: "Death", minLevel: 3 }],
    desc:    `Spreads a contagious rot that slowly drains strength and vitality from a target (or small group), reducing their maximum hit points temporarily and causing ongoing necrotic-like damage until cured.`,
    scaling: null,
  },
  {
    id:      "grave-omen",
    name:    "Grave Omen",
    cost:    15,
    wells:   [{ name: "Death", minLevel: 3 }],
    desc:    `Divines portents from the dead or near-death states, granting foresight about impending death (e.g., vulnerability to a specific attack type) or revealing hidden weaknesses tied to a creature's mortality.`,
    scaling: null,
  },
  {
    id:      "enfeebling-miasma",
    name:    "Enfeebling Miasma",
    cost:    20,
    wells:   [{ name: "Death", minLevel: 4 }],
    desc:    `Releases a cloud of sickly vapor that saps physical and mental resilience, imposing exhaustion levels or reducing ability scores as illness takes hold rapidly.`,
    scaling: null,
  },
  {
    id:      "soul-echo",
    name:    "Soul Echo",
    cost:    20,
    wells:   [{ name: "Death", minLevel: 4 }],
    desc:    `Summons a faint, non-corporeal echo of a dead soul to witness events or answer yes/no questions about their life/death, providing insight without any resurrection or control.`,
    scaling: null,
  },
  {
    id:      "decay-pulse",
    name:    "Decay Pulse",
    cost:    25,
    wells:   [{ name: "Death", minLevel: 5 }],
    desc:    `Sends out a wave of entropic energy that accelerates natural breakdown in living targets (aging them slightly, causing limbs to weaken, or objects to corrode), dealing damage that ignores some resistances and lingers.`,
    scaling: null,
  },
  {
    id:      "mortal-coil-snare",
    name:    "Mortal Coil Snare",
    cost:    25,
    wells:   [{ name: "Death", minLevel: 5 }],
    desc:    `Targets a creature nearing death, briefly stalling their demise to allow a natural resurrection window (e.g., stabilizing a dying ally without magical revival spells) or forcing an enemy into a fragile state where death comes faster.`,
    scaling: null,
  },
  {
    id:      "virulent-outbreak",
    name:    "Virulent Outbreak",
    cost:    30,
    wells:   [{ name: "Death", minLevel: 6 }],
    desc:    `Unleashes a powerful, spreading illness that infects multiple targets, causing escalating symptoms (blinding, paralyzing, or necrotic damage) and potentially jumping to new hosts if not contained.`,
    scaling: null,
  },
  {
    id:      "death-s-whisper",
    name:    "Death's Whisper",
    cost:    30,
    wells:   [{ name: "Death", minLevel: 6 }],
    desc:    `Communicates with multiple departed souls in an area, piecing together fragmented knowledge, warnings, or secrets from the dead to uncover hidden truths or predict fatal events.`,
    scaling: null,
  },
  {
    id:      "entropic-cascade",
    name:    "Entropic Cascade",
    cost:    35,
    wells:   [{ name: "Death", minLevel: 7 }],
    desc:    `Chains a debilitating curse through nearby creatures, where each affected target suffers worsening illness/decay that transfers partially to others if one falls, amplifying entropy across the battlefield.`,
    scaling: null,
  },
  {
    id:      "final-breath",
    name:    "Final Breath",
    cost:    35,
    wells:   [{ name: "Death", minLevel: 7 }],
    desc:    `Accelerates a target's life cycle to the brink of natural death, forcing them to make saving throws against instant collapse (or granting an ally a momentary "second wind" revival if already dying, purely natural restoration).`,
    scaling: null,
  },
  {
    id:      "plague-dominion",
    name:    "Plague Dominion",
    cost:    40,
    wells:   [{ name: "Death", minLevel: 8 }],
    desc:    `Establishes a zone of rampant illness where diseases manifest spontaneously, weakening all living beings inside (allies can be excluded), with effects like constant damage, reduced healing received, and vulnerability to further Death magic.`,
    scaling: null,
  },
  {
    id:      "necrotic-insight",
    name:    "Necrotic Insight",
    cost:    40,
    wells:   [{ name: "Death", minLevel: 8 }],
    desc:    `Draws profound knowledge from the veil of death, allowing the caster to glimpse the "death moment" of any creature (past, present, or fated), revealing immunities, fears, or fatal flaws for tactical advantage.`,
    scaling: null,
  },
  {
    id:      "aging-tempest",
    name:    "Aging Tempest",
    cost:    45,
    wells:   [{ name: "Death", minLevel: 9 }],
    desc:    `Calls forth a storm of accelerated entropy that rapidly ages and withers everything in a large area—living creatures suffer massive vitality loss, objects crumble, and time feels like decades pass in moments.`,
    scaling: null,
  },
  {
    id:      "threshold-return",
    name:    "Threshold Return",
    cost:    45,
    wells:   [{ name: "Death", minLevel: 9 }],
    desc:    `Pulls a recently deceased soul back across the threshold in a natural, non-undead resurrection (limited to very recent deaths, high cost/risk, no control over the revived), or forces an enemy soul to confront their own mortality, potentially causing instant death from overwhelming despair/entropy.`,
    scaling: null,
  },
  {
    id:      "erosion",
    name:    "Erosion",
    cost:    50,
    wells:   [{ name: "Death", minLevel: 10 }],
    desc:    `Destroys structures in a 500-meter radius over the course of 10 turns. Structures erode away; the caster can choose to exempt specific structures.`,
    scaling: null,
  },
  {
    id:      "cripple",
    name:    "Cripple",
    cost:    50,
    wells:   [{ name: "Death", minLevel: 10 }],
    desc:    `Choose one target. They must make a Constitution saving throw with DC = level×10. On pass, the effect lasts 3 turns. On fail, the crippling is permanent. Roll 1d10 for effect:\\n\\n1: Tremors in hands — Strength save DC 50 to hold objects; −5 to item use on success.\\n2: Impaired leg — Speed halved; kicking DC +10.\\n3: Thinned blood — double damage from bruising or bleeding.\\n4: Endurance failure — must rest 1 hour per 10 minutes of movement. Exceeding 1 hour: −5 to skill checks. Exceeding 2 hours: Willpower save DC 10+5 per 10 min or pass out.\\n5: EDS (bones).\\n6: EDS (muscles).\\n7: EDS (veins).\\n8: Paralysis.\\n9: Broken arm.\\n10: Extra teeth.`,
    scaling: null,
  },
  {
    id:      "wither-glare",
    name:    "Wither Glare",
    cost:    10,
    wells:   [{ name: "Death", minLevel: 1 }, { name: "Day", minLevel: 1 }],
    desc:    `A revealing stare that accelerates minor decay on a target, causing illness-like fatigue in bright light.`,
    scaling: null,
  },
  {
    id:      "plague-bind",
    name:    "Plague Bind",
    cost:    30,
    wells:   [{ name: "Death", minLevel: 3 }, { name: "Night", minLevel: 1 }],
    desc:    `Shadows infused with illness restrain and infect a target, spreading rot in darkness over time.`,
    scaling: null,
  },
  {
    id:      "entropy-lash",
    name:    "Entropy Lash",
    cost:    40,
    wells:   [{ name: "Death", minLevel: 4 }, { name: "Chaos", minLevel: 1 }],
    desc:    `Unstable wild energy whips out to curse with chaotic decay, random illness symptoms (fever, weakness, etc.).`,
    scaling: null,
  },
  {
    id:      "vitality-siphon",
    name:    "Vitality Siphon",
    cost:    60,
    wells:   [{ name: "Death", minLevel: 6 }, { name: "Life", minLevel: 1 }],
    desc:    `Drains a sliver of life force as illness, weakening healing while stabilizing the caster's own natural vitality.`,
    scaling: null,
  },
  {
    id:      "miasma-vortex",
    name:    "Miasma Vortex",
    cost:    80,
    wells:   [{ name: "Death", minLevel: 8 }, { name: "Arcane", minLevel: 1 }],
    desc:    `Raw magical winds carry entropic illness, eroding enemies in an area with escalating decay damage.`,
    scaling: null,
  },
  {
    id:      "terminal-omen",
    name:    "Terminal Omen",
    cost:    90,
    wells:   [{ name: "Death", minLevel: 9 }, { name: "Time", minLevel: 1 }],
    desc:    `Accelerates a target's timeline toward decay's end, inflicting fatal illness previews from their future/past frailty.`,
    scaling: null,
  },
  {
    id:      "apocalyptic-blight",
    name:    "Apocalyptic Blight",
    cost:    100,
    wells:   [{ name: "Death", minLevel: 10 }, { name: "Fortitude", minLevel: 1 }],
    desc:    `Fortified curse wave hardens decay into unbreakable illness, crippling physical resilience permanently until cured.`,
    scaling: null,
  },
  {
    id:      "minor-buff",
    name:    "Minor Buff",
    cost:    5,
    wells:   [{ name: "Fortitude", minLevel: 1 }],
    desc:    `You and one other you can touch get +1 damage for the next 5 attacks.`,
    scaling: `+1 mana → +1 attack; +2 mana → +1 damage`,
  },
  {
    id:      "crackle",
    name:    "Crackle",
    cost:    5,
    wells:   [{ name: "Fortitude", minLevel: 1 }],
    desc:    `On your next hit, the enemy rolls their Constitution vs DC 10. On failure, they cannot attack you for one attack turn.`,
    scaling: `+1 mana → +1 to DC`,
  },
  {
    id:      "iron-skin",
    name:    "Iron Skin",
    cost:    10,
    wells:   [{ name: "Fortitude", minLevel: 2 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "edge-of-fury",
    name:    "Edge of Fury",
    cost:    10,
    wells:   [{ name: "Fortitude", minLevel: 2 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "titan-s-grip",
    name:    "Titan's Grip",
    cost:    15,
    wells:   [{ name: "Fortitude", minLevel: 3 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "enduring-vigor",
    name:    "Enduring Vigor",
    cost:    15,
    wells:   [{ name: "Fortitude", minLevel: 3 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "thunderous-strike",
    name:    "Thunderous Strike",
    cost:    20,
    wells:   [{ name: "Fortitude", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "unyielding-stance",
    name:    "Unyielding Stance",
    cost:    20,
    wells:   [{ name: "Fortitude", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "giant-s-stride",
    name:    "Giant's Stride",
    cost:    25,
    wells:   [{ name: "Fortitude", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "adamant-blade",
    name:    "Adamant Blade",
    cost:    25,
    wells:   [{ name: "Fortitude", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "fortified-form",
    name:    "Fortified Form",
    cost:    30,
    wells:   [{ name: "Fortitude", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "rending-edge",
    name:    "Rending Edge",
    cost:    30,
    wells:   [{ name: "Fortitude", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "colossus-might",
    name:    "Colossus Might",
    cost:    35,
    wells:   [{ name: "Fortitude", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "indomitable-will",
    name:    "Indomitable Will",
    cost:    35,
    wells:   [{ name: "Fortitude", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "elemental-forge",
    name:    "Elemental Forge",
    cost:    40,
    wells:   [{ name: "Fortitude", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "titanic-resilience",
    name:    "Titanic Resilience",
    cost:    40,
    wells:   [{ name: "Fortitude", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "apex-warrior",
    name:    "Apex Warrior",
    cost:    45,
    wells:   [{ name: "Fortitude", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "worldbreaker-infusion",
    name:    "Worldbreaker Infusion",
    cost:    45,
    wells:   [{ name: "Fortitude", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "crack-the-world",
    name:    "Crack the World",
    cost:    50,
    wells:   [{ name: "Fortitude", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "indomitable-apex",
    name:    "Indomitable Apex",
    cost:    50,
    wells:   [{ name: "Fortitude", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "stone-ward",
    name:    "Stone Ward",
    cost:    20,
    wells:   [{ name: "Fortitude", minLevel: 2 }, { name: "Order", minLevel: 2 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "thunder-guard",
    name:    "Thunder Guard",
    cost:    40,
    wells:   [{ name: "Fortitude", minLevel: 4 }, { name: "Arcane", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "endure-shadows",
    name:    "Endure Shadows",
    cost:    50,
    wells:   [{ name: "Fortitude", minLevel: 5 }, { name: "Night", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "vital-bastion",
    name:    "Vital Bastion",
    cost:    70,
    wells:   [{ name: "Fortitude", minLevel: 7 }, { name: "Life", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "temporal-harden",
    name:    "Temporal Harden",
    cost:    80,
    wells:   [{ name: "Fortitude", minLevel: 8 }, { name: "Time", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "unbreakable-colossus",
    name:    "Unbreakable Colossus",
    cost:    100,
    wells:   [{ name: "Fortitude", minLevel: 10 }, { name: "Chaos", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "minor-heal",
    name:    "Minor Heal",
    cost:    5,
    wells:   [{ name: "Life", minLevel: 1 }],
    desc:    `Choose yourself or another you can see. Heal 1d10 damage, leaving a scab and halting bleedout. Works on Common injuries.`,
    scaling: `+1 mana → +1 to heal roll`,
  },
  {
    id:      "sprout",
    name:    "Sprout",
    cost:    5,
    wells:   [{ name: "Life", minLevel: 1 }],
    desc:    `In a 5×5 meter area, make plants begin to sprout. Full grown in 5 rounds, growing through anything in their path. Anyone who ends their turn in the square must make a Speed save or take 1d10 damage.`,
    scaling: `+1 mana → +1×1 meter area, or +1d10 damage (up to 10d10)`,
  },
  {
    id:      "vital-surge",
    name:    "Vital Surge",
    cost:    10,
    wells:   [{ name: "Life", minLevel: 2 }],
    desc:    `Channel a burst of life energy to heal harsh wounds and grant 1d10 temporary HP. Alternatively, enchant a weapon with poison (1d10+Life damage per round) or lifesteal (1d10+Life HP returned on hit).`,
    scaling: null,
  },
  {
    id:      "blooming-ward",
    name:    "Blooming Ward",
    cost:    10,
    wells:   [{ name: "Life", minLevel: 2 }],
    desc:    `Surround an ally with protective flowers that pulse a healing aura in a 20-meter radius. Heals 1d10÷2 per pulse, once per round. Also grants 5-round resistance to poisons and diseases. Wilts if hostile plants of a higher cast level appear nearby.`,
    scaling: null,
  },
  {
    id:      "regenerative-pulse",
    name:    "Regenerative Pulse",
    cost:    15,
    wells:   [{ name: "Life", minLevel: 3 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "venomous-thorn",
    name:    "Venomous Thorn",
    cost:    15,
    wells:   [{ name: "Life", minLevel: 3 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "mending-growth",
    name:    "Mending Growth",
    cost:    20,
    wells:   [{ name: "Life", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "toxic-cloud",
    name:    "Toxic Cloud",
    cost:    20,
    wells:   [{ name: "Life", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "life-infusion",
    name:    "Life Infusion",
    cost:    25,
    wells:   [{ name: "Life", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "corrosive-bloom",
    name:    "Corrosive Bloom",
    cost:    25,
    wells:   [{ name: "Life", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "restorative-aura",
    name:    "Restorative Aura",
    cost:    30,
    wells:   [{ name: "Life", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "necrotic-venom",
    name:    "Necrotic Venom",
    cost:    30,
    wells:   [{ name: "Life", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "verdant-renewal",
    name:    "Verdant Renewal",
    cost:    35,
    wells:   [{ name: "Life", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "plague-of-vitality",
    name:    "Plague of Vitality",
    cost:    35,
    wells:   [{ name: "Life", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "eternal-spring",
    name:    "Eternal Spring",
    cost:    40,
    wells:   [{ name: "Life", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "blightstorm",
    name:    "Blightstorm",
    cost:    40,
    wells:   [{ name: "Life", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "soulmend-cascade",
    name:    "Soulmend Cascade",
    cost:    45,
    wells:   [{ name: "Life", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "virulent-dominion",
    name:    "Virulent Dominion",
    cost:    45,
    wells:   [{ name: "Life", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "life-transference",
    name:    "Life Transference",
    cost:    50,
    wells:   [{ name: "Life", minLevel: 10 }],
    desc:    `Choose an amount of your HP and give it to anyone you can see within 100 meters. They heal double the amount given. If you give until you hit 0, go unconscious and maintain 1 HP. If you force yourself below 0, stay at 0 and proceed with death opportunities.`,
    scaling: null,
  },
  {
    id:      "extinction",
    name:    "Extinction",
    cost:    50,
    wells:   [{ name: "Life", minLevel: 10 }],
    desc:    `A foul energy seeps from you as all living things within 100 meters — including you — are marked for extinction. Over 10 turns, each turn decreases each affected creature's HP by 1/10 of their maximum. Can only be stopped by breaking the curse, making a wish, or cancelling the spell before turn 10.`,
    scaling: null,
  },
  {
    id:      "thorn-shield",
    name:    "Thorn Shield",
    cost:    10,
    wells:   [{ name: "Life", minLevel: 1 }, { name: "Fortitude", minLevel: 1 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "bloom-reveal",
    name:    "Bloom Reveal",
    cost:    30,
    wells:   [{ name: "Life", minLevel: 3 }, { name: "Day", minLevel: 3 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "toxin-surge",
    name:    "Toxin Surge",
    cost:    50,
    wells:   [{ name: "Life", minLevel: 5 }, { name: "Chaos", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "regrowth-bind",
    name:    "Regrowth Bind",
    cost:    60,
    wells:   [{ name: "Life", minLevel: 6 }, { name: "Death", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "eternal-grove",
    name:    "Eternal Grove",
    cost:    80,
    wells:   [{ name: "Life", minLevel: 8 }, { name: "Time", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "genesis-overload",
    name:    "Genesis Overload",
    cost:    100,
    wells:   [{ name: "Life", minLevel: 10 }, { name: "Order", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "palm-trick",
    name:    "Palm Trick",
    cost:    5,
    wells:   [{ name: "Night", minLevel: 1 }],
    desc:    `Manufacture an illusion in your palm to create a false item or hide one for an hour.`,
    scaling: `+1 mana → +10 minutes duration`,
  },
  {
    id:      "dim",
    name:    "Dim",
    cost:    5,
    wells:   [{ name: "Night", minLevel: 1 }],
    desc:    `Reduce all light in 50 meters by one light level.`,
    scaling: `+1 mana → +5 meters range`,
  },
  {
    id:      "minor-illusion",
    name:    "Minor Illusion",
    cost:    10,
    wells:   [{ name: "Night", minLevel: 2 }],
    desc:    `Manufacture an illusion that takes up 1×1 meters, making false objects and creatures or hiding something for an hour.`,
    scaling: `+1 mana → +10 minutes duration`,
  },
  {
    id:      "shadow-veil",
    name:    "Shadow Veil",
    cost:    10,
    wells:   [{ name: "Night", minLevel: 2 }],
    desc:    `Wrap the caster or an ally in shadows. Enemies have disadvantage hitting the concealed person in low light or darker.`,
    scaling: null,
  },
  {
    id:      "phantom-whisper",
    name:    "Phantom Whisper",
    cost:    15,
    wells:   [{ name: "Night", minLevel: 3 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "eclipse-grasp",
    name:    "Eclipse Grasp",
    cost:    15,
    wells:   [{ name: "Night", minLevel: 3 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "illusion",
    name:    "Illusion",
    cost:    20,
    wells:   [{ name: "Night", minLevel: 4 }],
    desc:    `Manufacture an illusion that takes up 5×5 meters, making false objects and creatures or hiding something for an hour.`,
    scaling: `+1 mana → +10 minutes duration`,
  },
  {
    id:      "mirage-shift",
    name:    "Mirage Shift",
    cost:    20,
    wells:   [{ name: "Night", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "darkness",
    name:    "Darkness",
    cost:    25,
    wells:   [{ name: "Night", minLevel: 5 }],
    desc:    `Reduce light levels in 50 meters down to darkness. Areas that were darkness become absolute darkness.`,
    scaling: `+1 mana → +5 meters range`,
  },
  {
    id:      "nocturnal-shroud",
    name:    "Nocturnal Shroud",
    cost:    25,
    wells:   [{ name: "Night", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "major-illusion",
    name:    "Major Illusion",
    cost:    30,
    wells:   [{ name: "Night", minLevel: 6 }],
    desc:    `Manufacture an illusion that takes up 10×10 meters, making false objects and creatures or hiding something for an hour.`,
    scaling: `+1 mana → +10 minutes duration`,
  },
  {
    id:      "terror-phantom",
    name:    "Terror Phantom",
    cost:    30,
    wells:   [{ name: "Night", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "shadow-puppet",
    name:    "Shadow Puppet",
    cost:    35,
    wells:   [{ name: "Night", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "abyssal-drain",
    name:    "Abyssal Drain",
    cost:    35,
    wells:   [{ name: "Night", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "blackout",
    name:    "Blackout",
    cost:    40,
    wells:   [{ name: "Night", minLevel: 8 }],
    desc:    `Reduce light levels in 50 meters to absolute darkness.`,
    scaling: `+1 mana → +5 meters range`,
  },
  {
    id:      "erasure",
    name:    "Erasure",
    cost:    40,
    wells:   [{ name: "Night", minLevel: 8 }],
    desc:    `Eliminate your sight, sound, tracks, smell, and touch for 10 minutes.`,
    scaling: `+1 mana → +5 minutes; +5 mana → +1 additional creature`,
  },
  {
    id:      "master-illusion",
    name:    "Master Illusion",
    cost:    45,
    wells:   [{ name: "Night", minLevel: 9 }],
    desc:    `Create or hide anything within a 50×50×50 meter block for an hour.`,
    scaling: `+1 mana → +10 minutes duration`,
  },
  {
    id:      "eternal-nightfall",
    name:    "Eternal Nightfall",
    cost:    45,
    wells:   [{ name: "Night", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "darkrise",
    name:    "Darkrise",
    cost:    50,
    wells:   [{ name: "Night", minLevel: 10 }],
    desc:    `In a 100×100 meter space, everything turns dark. A false moon rises at the center and turns deep red. The darkness cannot be seen through except by a vision spell of equal or higher level — except by the caster, who can see all clearly. The moon reveals the vital points of all creatures in the area, lowering called-shot DCs by 5. Lasts 12 hours.`,
    scaling: `+1 mana → +10 meters space, −1 to called-shot DC, or +1 hour duration`,
  },
  {
    id:      "psychosis",
    name:    "Psychosis",
    cost:    50,
    wells:   [{ name: "Night", minLevel: 10 }],
    desc:    `Choose one target. They make a Willpower save of DC = level×10. Passed: effect lasts 1 minute. Failed: permanent. Roll 1d10:\\n\\n1: Constant voices and sounds — auditory skill checks −20.\\n2: Flees water sources until 100 meters away; no other actions.\\n3: Sees visions — visual checks −20.\\n4: Flees fire sources until 100 meters away; no other actions.\\n5: Believes everything is their fault — social skills −20.\\n6: Flees any area with 3+ creatures in 50 meters until 3 or fewer remain.\\n7: Flees any area with fewer than 2 creatures and 4 structures until corrected or indoors.\\n8: Intelligence save if something moves 2× speed or flashes; DC 10, +5 per fail. Seizure lasts 10 seconds per 5 under DC; xd10 damage where x = under gap ÷ 5. If damage exceeds 100, temporary amnesia for 5+ minutes.\\n9: Urge to eat an inedible object; Willpower save DC = level×10.\\n10: Amnesia — cannot see sheet data; must rediscover skills as they use them.`,
    scaling: null,
  },
  {
    id:      "fade-step",
    name:    "Fade Step",
    cost:    10,
    wells:   [{ name: "Night", minLevel: 1 }, { name: "Time", minLevel: 1 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "phantom-guard",
    name:    "Phantom Guard",
    cost:    40,
    wells:   [{ name: "Night", minLevel: 4 }, { name: "Fortitude", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "dark-insight",
    name:    "Dark Insight",
    cost:    50,
    wells:   [{ name: "Night", minLevel: 5 }, { name: "Day", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "abyss-cloak",
    name:    "Abyss Cloak",
    cost:    70,
    wells:   [{ name: "Night", minLevel: 7 }, { name: "Death", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "nightmare-realm",
    name:    "Nightmare Realm",
    cost:    90,
    wells:   [{ name: "Night", minLevel: 9 }, { name: "Chaos", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "void-eclipse",
    name:    "Void Eclipse",
    cost:    100,
    wells:   [{ name: "Night", minLevel: 10 }, { name: "Day", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "stack",
    name:    "Stack",
    cost:    5,
    wells:   [{ name: "Order", minLevel: 1 }],
    desc:    `Instantly stack and sort anything into even piles within a 50×50 meter radius, condensing to within 1×1 meter if possible without injury.`,
    scaling: `+1 mana → +5 meters range`,
  },
  {
    id:      "suggest",
    name:    "Suggest",
    cost:    5,
    wells:   [{ name: "Order", minLevel: 1 }],
    desc:    `Roll your Order vs their Willpower. If the target fails, you implant a suggestion in their mind. The suggestion will be followed if it comes up and is not against their best interest (cannot cause intentional harm to them or their allies).`,
    scaling: null,
  },
  {
    id:      "align",
    name:    "Align",
    cost:    10,
    wells:   [{ name: "Order", minLevel: 2 }],
    desc:    `Force medium items into perfect alignment, or give an ally perfect clarity granting an extra 1d10 to their next mental check.`,
    scaling: null,
  },
  {
    id:      "command-echo",
    name:    "Command Echo",
    cost:    10,
    wells:   [{ name: "Order", minLevel: 2 }],
    desc:    `Issue a short verbal command that echoes in the target's mind, compelling a simple action (Drop Item, Step Back, Kneel, etc.). Roll Order + spell level vs their Willpower.`,
    scaling: null,
  },
  {
    id:      "coordinated-strike",
    name:    "Coordinated Strike",
    cost:    15,
    wells:   [{ name: "Order", minLevel: 3 }],
    desc:    `Link mentally with your allies for synchronized fighting without alerting the enemy. When one person hits a target, all others gain 1d10 extra on attacks against the same target. Lasts 3 rounds.`,
    scaling: null,
  },
  {
    id:      "enforce-discipline",
    name:    "Enforce Discipline",
    cost:    15,
    wells:   [{ name: "Order", minLevel: 3 }],
    desc:    `Prevents the target from experiencing magical wild surges. If used on an enemy, roll your Order against their Chaos.`,
    scaling: null,
  },
  {
    id:      "pattern-bind",
    name:    "Pattern Bind",
    cost:    20,
    wells:   [{ name: "Order", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "compel-truth",
    name:    "Compel Truth",
    cost:    20,
    wells:   [{ name: "Order", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "regiment-aura",
    name:    "Regiment Aura",
    cost:    25,
    wells:   [{ name: "Order", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "override-will",
    name:    "Override Will",
    cost:    25,
    wells:   [{ name: "Order", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "symmetry-shield",
    name:    "Symmetry Shield",
    cost:    30,
    wells:   [{ name: "Order", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "mass-suggestion",
    name:    "Mass Suggestion",
    cost:    30,
    wells:   [{ name: "Order", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "absolute-hierarchy",
    name:    "Absolute Hierarchy",
    cost:    35,
    wells:   [{ name: "Order", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "restructure-reality",
    name:    "Restructure Reality",
    cost:    35,
    wells:   [{ name: "Order", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "unyielding-edict",
    name:    "Unyielding Edict",
    cost:    40,
    wells:   [{ name: "Order", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "orchestrate-fate",
    name:    "Orchestrate Fate",
    cost:    40,
    wells:   [{ name: "Order", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "total-dominion",
    name:    "Total Dominion",
    cost:    45,
    wells:   [{ name: "Order", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "cosmic-alignment",
    name:    "Cosmic Alignment",
    cost:    45,
    wells:   [{ name: "Order", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "obey",
    name:    "Obey",
    cost:    50,
    wells:   [{ name: "Order", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "omega",
    name:    "Omega",
    cost:    50,
    wells:   [{ name: "Order", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "surface-scan",
    name:    "Surface Scan",
    cost:    10,
    wells:   [{ name: "Order", minLevel: 1 }, { name: "Day", minLevel: 1 }],
    desc:    `In a 50-meter radius, reveals to you the surface thoughts or emotions of one creature you can see. The surface thought will be clear to you.`,
    scaling: null,
  },
  {
    id:      "thought-echo",
    name:    "Thought Echo",
    cost:    30,
    wells:   [{ name: "Order", minLevel: 3 }, { name: "Time", minLevel: 3 }],
    desc:    `Choose one of two effects:\\n\\n1. Pull up a past thought (like a plan) from within the last 24 hours.\\n2. Implant a thought the target believes is their own.\\n\\nIf the target is unwilling, roll your Order vs their Willpower.`,
    scaling: null,
  },
  {
    id:      "deceptive-probe",
    name:    "Deceptive Probe",
    cost:    40,
    wells:   [{ name: "Order", minLevel: 4 }, { name: "Night", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "future-intent",
    name:    "Future Intent",
    cost:    60,
    wells:   [{ name: "Order", minLevel: 6 }, { name: "Time", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "mind-lattice",
    name:    "Mind Lattice",
    cost:    70,
    wells:   [{ name: "Order", minLevel: 7 }, { name: "Day", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "psychic-dominion",
    name:    "Psychic Dominion",
    cost:    90,
    wells:   [{ name: "Order", minLevel: 9 }, { name: "Night", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "stutter",
    name:    "Stutter",
    cost:    5,
    wells:   [{ name: "Time", minLevel: 1 }],
    desc:    `Pause an enemy action by 1 second as a reaction. Adds +1 per second to the enemy's target's DC.`,
    scaling: `+2 mana → +1 second pause`,
  },
  {
    id:      "blink",
    name:    "Blink",
    cost:    5,
    wells:   [{ name: "Time", minLevel: 1 }],
    desc:    `Teleport up to 10 meters away.`,
    scaling: `+1 mana → +1 meter range`,
  },
  {
    id:      "foresight-flicker",
    name:    "Foresight Flicker",
    cost:    10,
    wells:   [{ name: "Time", minLevel: 2 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "echo-step",
    name:    "Echo Step",
    cost:    10,
    wells:   [{ name: "Time", minLevel: 2 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "temporal-lurch",
    name:    "Temporal Lurch",
    cost:    15,
    wells:   [{ name: "Time", minLevel: 3 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "past-whisper",
    name:    "Past Whisper",
    cost:    15,
    wells:   [{ name: "Time", minLevel: 3 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "future-thread",
    name:    "Future Thread",
    cost:    20,
    wells:   [{ name: "Time", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "momentary-reversal",
    name:    "Momentary Reversal",
    cost:    20,
    wells:   [{ name: "Time", minLevel: 4 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "chrono-pulse",
    name:    "Chrono Pulse",
    cost:    25,
    wells:   [{ name: "Time", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "memory-glimpse",
    name:    "Memory Glimpse",
    cost:    25,
    wells:   [{ name: "Time", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "temporal-anchor",
    name:    "Temporal Anchor",
    cost:    30,
    wells:   [{ name: "Time", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "aging-surge",
    name:    "Aging Surge",
    cost:    30,
    wells:   [{ name: "Time", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "fate-weave",
    name:    "Fate Weave",
    cost:    35,
    wells:   [{ name: "Time", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "past-echo-summon",
    name:    "Past Echo Summon",
    cost:    35,
    wells:   [{ name: "Time", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "time-distortion-field",
    name:    "Time Distortion Field",
    cost:    40,
    wells:   [{ name: "Time", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "regressive-touch",
    name:    "Regressive Touch",
    cost:    40,
    wells:   [{ name: "Time", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "chronal-dominion",
    name:    "Chronal Dominion",
    cost:    45,
    wells:   [{ name: "Time", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "timeline-fracture",
    name:    "Timeline Fracture",
    cost:    45,
    wells:   [{ name: "Time", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "time-break",
    name:    "Time Break",
    cost:    50,
    wells:   [{ name: "Time", minLevel: 10 }],
    desc:    `Choose 1 target. They make a Wisdom save vs level×5. Send the target forward in time by level×10 years. On failure, they are aged to a teenager by their race's standards. The aging can only be reversed by a curse breaker, a wish, or natural re-aging.`,
    scaling: null,
  },
  {
    id:      "time-ravage",
    name:    "Time Ravage",
    cost:    50,
    wells:   [{ name: "Time", minLevel: 10 }],
    desc:    `Choose 1 target. They make a Wisdom save vs level×5. Send the target back in time by level×10 years. On failure, they are aged to 10 days before their dying breath. Can only be reversed by a curse breaker, the healing waters, or a wish.`,
    scaling: null,
  },
  {
    id:      "precog-dodge",
    name:    "Precog Dodge",
    cost:    20,
    wells:   [{ name: "Time", minLevel: 2 }, { name: "Fortitude", minLevel: 2 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "echo-bind",
    name:    "Echo Bind",
    cost:    30,
    wells:   [{ name: "Time", minLevel: 3 }, { name: "Order", minLevel: 3 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "flux-pulse",
    name:    "Flux Pulse",
    cost:    60,
    wells:   [{ name: "Time", minLevel: 6 }, { name: "Arcane", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "past-haunt",
    name:    "Past Haunt",
    cost:    70,
    wells:   [{ name: "Time", minLevel: 7 }, { name: "Night", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "life-rewind",
    name:    "Life Rewind",
    cost:    80,
    wells:   [{ name: "Time", minLevel: 8 }, { name: "Life", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "eternity-weave",
    name:    "Eternity Weave",
    cost:    100,
    wells:   [{ name: "Time", minLevel: 10 }, { name: "Day", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "animate-carrion",
    name:    "Animate Carrion",
    cost:    75,
    wells:   [{ name: "Death", minLevel: 5 }, { name: "Life", minLevel: 5 }, { name: "Time", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "grave-bind",
    name:    "Grave Bind",
    cost:    75,
    wells:   [{ name: "Time", minLevel: 5 }, { name: "Death", minLevel: 5 }, { name: "Life", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "skeletal-legion",
    name:    "Skeletal Legion",
    cost:    90,
    wells:   [{ name: "Death", minLevel: 6 }, { name: "Time", minLevel: 6 }, { name: "Life", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "corrupted-revival",
    name:    "Corrupted Revival",
    cost:    90,
    wells:   [{ name: "Life", minLevel: 6 }, { name: "Death", minLevel: 6 }, { name: "Time", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "finger-of-undeath",
    name:    "Finger of Undeath",
    cost:    105,
    wells:   [{ name: "Death", minLevel: 7 }, { name: "Life", minLevel: 7 }, { name: "Time", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "temporal-wraith",
    name:    "Temporal Wraith",
    cost:    105,
    wells:   [{ name: "Time", minLevel: 7 }, { name: "Death", minLevel: 7 }, { name: "Life", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "create-greater-undead",
    name:    "Create Greater Undead",
    cost:    120,
    wells:   [{ name: "Death", minLevel: 8 }, { name: "Time", minLevel: 8 }, { name: "Life", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "soul-siphon-horde",
    name:    "Soul Siphon Horde",
    cost:    120,
    wells:   [{ name: "Life", minLevel: 8 }, { name: "Death", minLevel: 8 }, { name: "Time", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "lich-s-shadow",
    name:    "Lich's Shadow",
    cost:    135,
    wells:   [{ name: "Time", minLevel: 9 }, { name: "Life", minLevel: 9 }, { name: "Death", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "eternal-legion",
    name:    "Eternal Legion",
    cost:    135,
    wells:   [{ name: "Death", minLevel: 9 }, { name: "Time", minLevel: 9 }, { name: "Life", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "apocalypse-raise",
    name:    "Apocalypse Raise",
    cost:    150,
    wells:   [{ name: "Death", minLevel: 10 }, { name: "Life", minLevel: 10 }, { name: "Time", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "ascend-to-undeath",
    name:    "Ascend to Undeath",
    cost:    150,
    wells:   [{ name: "Time", minLevel: 10 }, { name: "Death", minLevel: 10 }, { name: "Life", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "summon-lesser-genie",
    name:    "Summon Lesser Genie",
    cost:    75,
    wells:   [{ name: "Chaos", minLevel: 5 }, { name: "Arcane", minLevel: 5 }, { name: "Order", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "twisted-wish",
    name:    "Twisted Wish",
    cost:    75,
    wells:   [{ name: "Order", minLevel: 5 }, { name: "Chaos", minLevel: 5 }, { name: "Arcane", minLevel: 5 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "elemental-binding",
    name:    "Elemental Binding",
    cost:    90,
    wells:   [{ name: "Arcane", minLevel: 6 }, { name: "Order", minLevel: 6 }, { name: "Chaos", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "genie-s-command",
    name:    "Genie's Command",
    cost:    90,
    wells:   [{ name: "Order", minLevel: 6 }, { name: "Arcane", minLevel: 6 }, { name: "Chaos", minLevel: 6 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "djinni-vortex",
    name:    "Djinni Vortex",
    cost:    105,
    wells:   [{ name: "Chaos", minLevel: 7 }, { name: "Arcane", minLevel: 7 }, { name: "Order", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "lamp-s-savant",
    name:    "Lamp's Savant",
    cost:    105,
    wells:   [{ name: "Arcane", minLevel: 7 }, { name: "Chaos", minLevel: 7 }, { name: "Order", minLevel: 7 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "ifrit-blaze",
    name:    "Ifrit Blaze",
    cost:    120,
    wells:   [{ name: "Arcane", minLevel: 8 }, { name: "Chaos", minLevel: 8 }, { name: "Order", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "ordered-mirage",
    name:    "Ordered Mirage",
    cost:    120,
    wells:   [{ name: "Order", minLevel: 8 }, { name: "Arcane", minLevel: 8 }, { name: "Chaos", minLevel: 8 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "marid-s-dominion",
    name:    "Marid's Dominion",
    cost:    135,
    wells:   [{ name: "Chaos", minLevel: 9 }, { name: "Order", minLevel: 9 }, { name: "Arcane", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "wish-cascade",
    name:    "Wish Cascade",
    cost:    135,
    wells:   [{ name: "Order", minLevel: 9 }, { name: "Chaos", minLevel: 9 }, { name: "Arcane", minLevel: 9 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "jann-s-eternal-bind",
    name:    "Jann's Eternal Bind",
    cost:    150,
    wells:   [{ name: "Arcane", minLevel: 10 }, { name: "Order", minLevel: 10 }, { name: "Chaos", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "ultimate-wish",
    name:    "Ultimate Wish",
    cost:    150,
    wells:   [{ name: "Chaos", minLevel: 10 }, { name: "Arcane", minLevel: 10 }, { name: "Order", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "create",
    name:    "Create",
    cost:    1000,
    wells:   [{ name: "Arcane", minLevel: 10 }, { name: "Chaos", minLevel: 10 }, { name: "Day", minLevel: 10 }, { name: "Death", minLevel: 10 }, { name: "Fortitude", minLevel: 10 }, { name: "Life", minLevel: 10 }, { name: "Night", minLevel: 10 }, { name: "Order", minLevel: 10 }, { name: "Time", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
  {
    id:      "destroy",
    name:    "Destroy",
    cost:    1000,
    wells:   [{ name: "Arcane", minLevel: 10 }, { name: "Chaos", minLevel: 10 }, { name: "Day", minLevel: 10 }, { name: "Death", minLevel: 10 }, { name: "Fortitude", minLevel: 10 }, { name: "Life", minLevel: 10 }, { name: "Night", minLevel: 10 }, { name: "Order", minLevel: 10 }, { name: "Time", minLevel: 10 }],
    desc:    ``,
    scaling: null,
  },
];